version: '3'

services:
  postgres:
    image: postgres
    container_name: 'postgres-links'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5433:5432'
  links-shortening-service:
    build:
      context: .
    container_name: 'links-shortener'
    depends_on:
      - postgres
    ports:
      - '8080:8080'